### ISSUE TITLE
This is server routing, not angular2 routing

### ISSUE THREAD

**Issue by klanglie** [damienbod/AspNet5IdentityServerAngularImplicitFlow#101]
Probably something simple I am missing here. Trying to figure out why the AngularClient app is not loading. I'll update if I figure this out.

**Comment by klanglie** [comment]
A temporary fix is to hard code webpack.config.js

module.exports = function(env) {
  //return require(`./config/webpack.${env}.js`)
    return require(`./config/webpack.dev.js`)
}

Otherwise env is undefined. Does anyone know why env is not being passed in correctly?

**Comment by hemiaoio** [comment]
Did you installed [NPMTaskRunner](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner)?

**Comment by Simplist9** [comment]
The temporary fix does not work for me.. @damienbod if you have time, can you look into the issue, please?
Thank you.

**Comment by damienbod** [comment]
@Simplist9 

Does the angular app build?

Try this from the command line
Open the Angular project folder when the csproj file is.

> npm install
> npm run build-dev

and try it again, sometimes the tools don't work inside VS, or aren't installed.

**Comment by Simplist9** [comment]
@damienbod 
Indeed, when i ran "npm run build-dev" inside the project file it worked.
Thank you very much!

**Comment by klanglie** [comment]
I just went through this again on another machine. I installed _NPM Task Runner v1.4.8.1.visix_, _yarn-1.7.0.msi_ and _webpack/webpack-cli_ globally. It is now running. It might be helpful to add setup instructions to the Readme file. Great example btw. Thanks so much!
