### ISSUE TITLE
How to run the application?

### ISSUE THREAD

**Issue by bhaidar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#105]
Hi,
I have both VS Code and VS 2017.

How to run the code and test the application? I put AngularClient and StsServerIdentity to run. But the Sts project defines the client with IP of the ASP.NET Core app and not the Angular app.

I am a bit confused on how to run the apps?

**Comment by damienbod** [comment]
Hi @bhaidar 

You need to build the angular app and and the APIs

Use npm to install the npm packages for the Angular client project. Then do an angular build, npm run build-dev, then build the .NET Core solution.

Start the 2 APIs, the STS server, and the Angular client. When you run it first, it should ask you the trust the iis express certs, and then it runs.

Greetings Damien

**Comment by bhaidar** [comment]
Hi @damienbod 
Perfect!

Let me summarize the steps here in case someone else faced the problem.

- Follow the instructions on the `README.md` file to restore .NET packages and do the migrations.
- Build the entire solution in Visual Studio
- From the command line, run `npm run build-env` to build the code and generate bundles
- Then simple configure Visual Studio to run multiple projects including StsServerIdentity, AngularClient, ResourceFileServer, and ResourceServer.

That's all!

Two things I noticed though:
- You make use of:
  ````JSON
  "ConnectionStrings": {
    "DefaultConnection": "__DefaultConnection__"
  }
  ````

  Is that an environment variable you set somewhere in production? 

- When the app first loads, the menu items are not showing (exception for languages). I look at the code, there is nothing hiding/showing them when the user is logged in or not. Why weren't visible at the beginning before signing in?

Thanks

**Comment by damienbod** [comment]
@bhaidar thanks

**Comment by bhaidar** [comment]
@damienbod 
Thanks. So basically I either make use of EV or provide a simple string for the ConnectionString for example. Correct?
