### ISSUE TITLE
How assign/manage User Claim from AspNetUserClaims?

### ISSUE THREAD

**Issue by Arpanx** [damienbod/AspNet5IdentityServerAngularImplicitFlow#106]
I do not understand much about these issues, but there is a question.

Now the Claims is assign in the hard code in IdentityWithAdditionalClaimsProfileService: IProfileService
This discourages us from administering Claims
Whether it is possible to make somehow that the Claims & Role it was possible to appoint editing IdentityServer database?

Thanks for your example, very well let me understand how to use Identity Server4.

**Comment by klanglie** [comment]
Hi @Arpanx. I was able to do this. But it requires work on your end. The ProfileService is meant only as an example. Once you start playing around with the Microsoft.Identity schema and classes you too can tap into this. I wish I could show you an example. But my project is not public.
