### ISSUE TITLE
Add npm install and npm run build-dev in AngularClient.csproj when app is building 

### ISSUE THREAD

**Issue by RafalDeveloper** [damienbod/AspNet5IdentityServerAngularImplicitFlow#113]
When application is open in debug mode via VS2017 https://localhost:44311/ there is error SCRIPT1004: SCRIPT1004: Expected ';'

**Comment by RafalDeveloper** [comment]
Ok. My mistake with use this solution correct. 

I have to do this - open AngularClient
1. npm install
2. npm run build-dev
3. Multiple Projects start: AngularClient, ResourceFileServer, ResourceServer, StsServerIdentity
4. Debug in VS 2017

and it`s working but could be better do this in AngularClient.csproj I would like to admit this project is great. Damien thanks for you hard work.

**Comment by workcontrolgit** [comment]
Thank you RafalDeveloper for spelling out the steps.  Just want to point out that I had to upgrade VS 2017 to version 15.9.5 in order to successfully run the Debug step 4.
