### ISSUE TITLE
Internal Error message localization 

### ISSUE THREAD

**Issue by saeidehv** [damienbod/AspNet5IdentityServerAngularImplicitFlow#118]
any recommendation for localization of error messages from UserManager like "the email is already taken"?

Thanks

**Comment by damienbod** [comment]
oh... I forgot to localize all of these :)

The strings are localized in Identity, we just need to find the key, and add a translation to our resx files. The keys are defined in the Resources.resx class in the Microsoft.Extensions.Identity.Core

https://github.com/aspnet/Identity/blob/master/src/Core/Resources.resx

I will translate these as well in the next while, or if you do it, maybe you could do a PR

Thanks for the pointer.

Or here's a translation example

https://github.com/fanruinet/Microsoft.Extensions.Identity.Core.zh-Hans

**Comment by saeidehv** [comment]
Thank you for the quick response.
Now in
 private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
we should add error.Code.

**Comment by damienbod** [comment]
This is ok, excpet for french, will update this when I get the translation, de and IT are complete.
