### ISSUE TITLE
ShowRecoveryCodesViewModel localization

### ISSUE THREAD

**Issue by athalius** [damienbod/AspNet5IdentityServerAngularImplicitFlow#120]
The localization for ShowRecoveryViewModel is broken in general - none of the localizations exist for the variables you have in there.

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/StsServerIdentity/Views/Manage/ShowRecoveryCodes.cshtml

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/StsServerIdentity/Resources/SharedResource.en-US.resx

**Comment by athalius** [comment]
I'd fix it myself, but you've used several languages I dont know, and Im not sure if this stuff was autogenerated from google translate or not.

**Comment by damienbod** [comment]
@athalius I look at this, the translations are done by native speakers, not google, so these should be correct. I'll check this. Thanks for reporting

**Comment by damienbod** [comment]
@athalius yep. these are missing... Thanks will start adding them

**Comment by damienbod** [comment]
Added the placeholders, will start chasing the translations now

**Comment by damienbod** [comment]
https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate/issues/46
