### ISSUE TITLE
Webpack dev server high cpu and memory

### ISSUE THREAD

**Issue by arimaze** [damienbod/AspNet5IdentityServerAngularImplicitFlow#126]
Hi,
I experience trouble debugging application espacially using debug mode i am always near 99%cpu used but if i remove webpack ton use angular json and ng serve all is ok

Do you have any idea why webpack dev sever take all cpu and memory ?

Br

**Comment by damienbod** [comment]
HI @arimaze 

No idea, I don't have this issue, would be interested if you see something.

Greetings Damien
