### ISSUE TITLE
How to send token from API to another

### ISSUE THREAD

**Issue by arimaze** [damienbod/AspNet5IdentityServerAngularImplicitFlow#127]
Hi Damien,

We would like to improve solution sending access token from API 1 to another API 2.

So, Summary workflow will be : Identy server connection > Angular > API 1 > API 2.

Do you know how to retrieve access token into API 1 ? because i think we only have ID_TOKEN.

Thanks and best regards

**Comment by damienbod** [comment]
Hi @arimaze when sending a token from one api to another api, you should create and new token and use this. This is a trusted API communicating with  a trusted API, ie, keep a secret. 

Something like this would be good:

https://github.com/damienbod/AspNetCoreHybridFlowWithApi/blob/master/WebMVCClient/ApiService.cs

And you need to add this client to the STS client. 
Client credentials flow

https://github.com/damienbod/AspNetCoreHybridFlowWithApi/blob/master/StsServer/Config.cs#L91-L98

Also the public access token should not work with the second API probably.

Gruss Damien
