### ISSUE TITLE
Single signon login form localization

### ISSUE THREAD

**Issue by saeidehv** [damienbod/AspNet5IdentityServerAngularImplicitFlow#128]
Hello,

We are using Identity server for Single signon and redirecting our users from CVent to our Identity server for authentication. I need to localized login page based on user IP address or set the locale as parameter in the Authentication URL link in CVent ( like :https://localhost:44323/Account/singlesignon?ui_locale=en-US") I do not know if I can do it.

Any recommendation for doing this?

Thanks,
Saeideh

**Comment by damienbod** [comment]
Yes this should work now

You can set the ui_locales parameter depending on the IP

Greetings Damien

**Comment by saeidehv** [comment]
Thanks
