### ISSUE TITLE
samesite flag chrome issue

### ISSUE THREAD

**Issue by saeidehv** [damienbod/AspNet5IdentityServerAngularImplicitFlow#145]
Hello Damien,

I have downloaded the latest version and I am running the StsServerIdentity as just start up project,
and enabled the samesite flags of my chrome ( Enable removing SameSite=None cookies
 and Cookies without SameSite must be secure)
I registered a new user successfully but when I login, the user is not showing up as login.
The User is empty in the context.
If I turn off the flags everything is working fine.
I'd be thankful if you can let me know what do you think about this issue?
 
Thank you,
Saeideh

**Comment by damienbod** [comment]
Hi @saeidehv 

I added a fix for the antiForegy cookie. The rest seems to be good. Could you try again?

If it still is not ok, could you send me the F12 info about which cookie causes the problem. Maybe also try to delete the old cookies before the test

Greetings Damien

**Comment by saeidehv** [comment]
Thank you Damien,
It is working now.
