### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by computercraft-co-nz** [damienbod/AspNet5IdentityServerAngularImplicitFlow#16]
I try to start without debugging the IdentityServerAspNet5 using IIS Express.
The first time it attempted to execute I was asked if I would like to install a security token.  I answered yes.
Thereafter and each subsequent time I attempt to start the app I get a http Error 500.19
The suspicious information on that page is the Config file  reads \\?\C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\IdentityServerAspNet5\wwwroot\web.config
Any hints on how to get past this point?

EDIT
If I try Start Debugging - The error message is "An error occurred attempting to determine the process id of the DNX" process hosting your application.

![error](https://cloud.githubusercontent.com/assets/5673116/14480191/93e0f726-017a-11e6-85fd-2a2ca8bfc102.png)

**Comment by damienbod** [comment]
Hi @computercraft-co-nz 

You need to change this in the config file and in the different startup class files. I also created the pfx key myself, this can be replaced by yours. The https ports used by you, will probably be different than the ports used be me, these also need to be changed to match you runtime, (all applications). I plan to move all the code configurations to a config files to make it easier to start. 

You should not see the C:\git\damienbod\AspNet5IdentityServerAngularImplicitFlow\src\IdentityServerAspNet5\wwwroot\web.config, I must have committed built solution file. Do a clean up, and a dnu restore.

Hope this helps

Greetings Damien

**Comment by computercraft-co-nz** [comment]
Hi Damien,
So just doing small steps and focusing on IndentityServerAspNet5.
This project does on have a config file (yes the other projects do have a config file). 
Checking the Startup it looks straight forward and cannot see any changes I should make?
I would have expected your pfx file would have worked, so I'm thinking why change it?
I have checked the port setting and they appear to be the same and all projects are pointing to the correct ports.  The screen shot showed up as 44345.
I don't believe you committed a build solution file, because the dependencies needed to be restored when I first opened the solution.  However I did do a cleanup and dnu restore.
 
If I attempt to debug the application and put a breakpoint on the startup.cs file, this breakpoint is never reached.  The application fails (error message in my first message) prior to hitting the breakpoint.

I'll persist tomorrow, but if you think of anything else, I'd love to hear from you.

__Allan

**Comment by computercraft-co-nz** [comment]
I have managed to get the applications working…
All the projects in the solution gave me an http Error 500.19.
So for each of the projects that I wanted to execute I did the following
	(a) Set as StartUp Project
	(b) Start without Debugging.  Received 500.19 error.
	(c) Close Browser.
	(d) Open application Properties -> Debug and remove the tick mark against Enable Anonymous Authentication.  Then save.
	(e) Start without Debugging.  Receive 401.2 error
	(f) Close Browser.
	(g) Re-Enabled Anonymous Authentication. Then save.
	(h) Start without Debugging. It works

Why?  I have no idea?  I am however now able to test Damien's work.

In the ResourceServer, change the config.json to suit your environment.

And it works as expected.  Well done Damien!

__Allan
