### ISSUE TITLE
Checking against a mix of roles/claims

### ISSUE THREAD

**Issue by weedkiller** [damienbod/AspNet5IdentityServerAngularImplicitFlow#166]
Hello, this is simply amazing and its kept current love it 🤟🏾 

I updated and for most of the code in Angular 11 I am able to check `*ngIf="isAuthenticated$ | async"` and single role with `*ngIf="hasAdminRole"` I followed your blog too... how do I check against a group/mix of roles and claims?

Also will it be the same with the new .NET core 6 coming or will it need to be modified since they have one code base for mobile and web

**Comment by damienbod** [comment]
Hi @weedkiller thanks

I would just create a helper function in angular which can be used in the ngIf

Greetings Damien

**Comment by weedkiller** [comment]
ok thanks @damienbod so could I pass it both roles and claims/policy in the same check `AccountingRole` and `AuditClaim`
