### ISSUE TITLE
External Providers

### ISSUE THREAD

**Issue by Sn3b** [damienbod/AspNet5IdentityServerAngularImplicitFlow#17]
Hi,

Great examples, thanks for that.

I'm trying to add external providers to your IdentityServer4 implementation but I cannot find the right way :(

I have added `Microsoft.AspNet.Authentication.Google` as a dependency and added the following to Startup.cs:

```csharp
    app.UseGoogleAuthentication( options =>
    {
        options.ClientId = "xxx";
        options.ClientSecret = "xxx";
    } );
```

Got the error "The 'SignInScheme' option must be provided." so I added the following too: `options.SignInScheme = "NoIdeaWhatToPutThereButItWorks";`.

Now it loads, but I have no idea what to do next :(

I'm trying to see how MVC6 does it but they use AspNet.Identity, which I think isn't ready for IdentityServer4, plus, I don't really want local registration anyway, I'd like to use external providers only.

Thanks.

**Comment by Sn3b** [comment]
I have also managed to get the buttons to render by copy/pasting the MVC6 code but using `Context.Authentication.GetAuthenticationSchemes()` instead of `SignInManager.GetExternalAuthenticationSchemes()`:

```csharp
    // UI/Login/Views/Index.cshtml
    var loginProviders = Context.Authentication.GetAuthenticationSchemes().ToList();
    if ( loginProviders.Count == 0 )
    {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkID=532715">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else
    {
        <form asp-controller="Account" asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
            <div>
                <p>
                    @foreach ( var provider in loginProviders )
                    {
                        <button type="submit" class="btn btn-default" name="provider" value="@provider.AuthenticationScheme" title="Log in using your @provider.DisplayName account">@provider.AuthenticationScheme</button>
                    }
                </p>
            </div>
        </form>
    }
```

I guess I have to create a controller now, but again when I look at how it's done in MVC6 I'm stuck because they use AspNet.Identity.

Found this interesting article but not sure if it's the right way to go: http://www.jerriepelser.com/blog/using-aspnet-oauth-providers-without-identity

**Comment by computercraft-co-nz** [comment]
Sn3b
Ben Foster has posted code for his SAAS kit. Included in the sample code is the Google oAuth middleware.  Check out https://github.com/saaskit/saaskit/tree/master/samples/AspNetMvcAuthDemo 
__Allan

**Comment by Sn3b** [comment]
@computercraft-co-nz thank! :)

**Comment by damienbod** [comment]
Hi @Sn3b  @computercraft-co-nz, sorry for the slow answer, was away. Thanks @computercraft-co-nz  for the good link. I'm am waiting till the next release of IdentityServer4 before investing any time in the identity area because I expect a lot to change here. The next release will be some time after ASP.NET Core RC2 release, so you could be waiting a long time for this.

Greetings Damien

**Comment by Sn3b** [comment]
@damienbod thanks for the answer, no problem for the delay, I am on holidays myself :package: 
Just to be sure, you prefer to wait for Identity to be ready then? No plan for social logins without Identity?

**Comment by damienbod** [comment]
@Sn3b I'm expecting something like this with the new ASP.NET Core libraries 

https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/CustomUserService/CustomUserService/Startup.cs

I do not plan to use any ASP.NET Core libraries for production until after RC2 release as RC2 is so different to RC1 and older versions. Seems like a new software to me. 

Greetings Damien

**Comment by Sn3b** [comment]
Thanks alot @damienbod! :)

**Comment by damienbod** [comment]
This should now be possible in the RC2 version of IdentityServer4. Is it ok to close this issue?

Greetings Damien

**Comment by Sn3b** [comment]
Sure :)
