### ISSUE TITLE
Use oidc-client

### ISSUE THREAD

**Issue by pontusr** [damienbod/AspNet5IdentityServerAngularImplicitFlow#20]
Hi!

Thanks for your work on this and your blog - they have both been a great resource for me in dealing with auth in ng2.

Not sure if you are actually trying to document how to implement the entire OIDC spec yourself. If not, it would be great to use the official" oidc-client. Any plans for that? That way we would get a lot of "freebies", like token renewal, token validation, better fragment handling...

https://github.com/IdentityModel/oidc-client-js

**Comment by damienbod** [comment]
Hi Thanks

Ye , the oidc-client is a cool library, looks really good. At present, I have no plans for this, I wanted to implement a log out first, and then the database for the users. 

Greetings Damien

**Comment by damienbod** [comment]
Hi @pontusr 

@jmurphzyo has a good repo here:

https://github.com/jmurphzyo/Angular2OidcClient

Is it ok to close this?

Greetings Damien

**Comment by pontusr** [comment]
Absolutely - we have it working fine since some time using the oidc-client-js library, very good library.
