### ISSUE TITLE
In the Angular2 client, a successful login returns to an undefined route

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#22]

**Comment by damienbod** [comment]
fixed

**Comment by ph1lolog1st** [comment]
Hi damienbod. Was update to rc5 the fix to this bug? What should I do to fix this bug, and don't update to rc5?

**Comment by damienbod** [comment]
Hi @ph1lolog1st 
my routing was defined incorrect

Greetings Damien

**Comment by ph1lolog1st** [comment]
damienbod, very thanks for quick replay. Could you say what exactly was wrong and why, please?

**Comment by ph1lolog1st** [comment]
@damienbod, can i fix this bug using router 3.0.0-beta.1?

**Comment by ph1lolog1st** [comment]
I found solution: window.location.href = "something". I think it is a poor solution, but it's work.
