### ISSUE TITLE
In AuthorizedCallback() --> router navigate to DataEventRecordsList don't work

### ISSUE THREAD

**Issue by cfm017** [damienbod/AspNet5IdentityServerAngularImplicitFlow#25]
In the method AuthorizedCallback() when the "authResponseIsValid" is true there are a command "this._router.navigate(['/dataeventrecords']);" --> this command don't work.

**Comment by damienbod** [comment]
This should work, I'll check this and get back to you.

This is defined here:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/Angular2Client/wwwroot/app/dataeventrecords/dataeventrecords.routes.ts

Greetings Damien

**Comment by cfm017** [comment]
I solved the problem :)

I’m implementing your architecture for my new project, I hope that we will have the final version of angular 2 soon. Thank you for your contribution

Best regards
Cristóbal

**Comment by damienbod** [comment]
Hi Cristóbal, cool

Greetings Damien
