### ISSUE TITLE
Cannot read out the profile information in angular2 client

### ISSUE THREAD

**Issue by alvachien** [damienbod/AspNet5IdentityServerAngularImplicitFlow#29]
Via the decoding, the profile information is missing meanwhile the OIDC_client can fetch anything out.
Any hint for it?

Thanks, Alva

**Comment by damienbod** [comment]
Hi @alvachien 

The user profile data can be got from the access_token. In this application the getDataFromToken in the security service returns the data from the access_token. You can make this public or access the data directly from the local storage.

Another possibility is to use the id_token and call a IdentityServer4 server method which returns the user data. 

Greetings Damien

**Comment by alvachien** [comment]
@damienbod Thanks so much for the hint.

Regards, Alva
