### ISSUE TITLE
.Net Core Identity, IdentityServer4 and AngularJS Authorization Query

### ISSUE THREAD

**Issue by richb78uk** [damienbod/AspNet5IdentityServerAngularImplicitFlow#33]
Hi,
I've got your sample AngularJS code working in my project at a basic level, it authenticates OK which is all fine, but I need to develop this a bit further, and looking for some pointers on the best way to do this.

Say for example I have a left had Nav bar and with 2 items "view" and "admin"  and I have 2 users ReadOnlyUser and AdminUser (admin user has role/claim of Admin) ReadOnlyUser doesn't.   I only want to show "admin" in the NavBar to AdminUser and protect the root /admin - what is the best way of doing this in Angular?

Thanks
Richard

**Comment by damienbod** [comment]
Hi Richard

You can implement a base controller and each angular controller can inherit from this. All your security logic can be implemented here and used in the views then, for example ng-if=hasUserReadRight() or hasUserWriteRight()

Greetings Damien

**Comment by damienbod** [comment]
@richb78uk  Can I close this?

**Comment by richb78uk** [comment]
Yes, I ended up going down Mvc route for a number of reasons!

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Dec 20, 2016 at 2:17 PM +0000, "damienbod" <notifications@github.com<mailto:notifications@github.com>> wrote:


@richb78uk<https://github.com/richb78uk> Can I close this?
