### ISSUE TITLE
Any chance can do an Ionic 2 or Electron example?

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#34]
Hi Damo,

keep up the fantastic work mate.

Any chance can do an Ionic 2 or Electron example?

cant seem to find anything out there, and wondering if you could please do one or point towards one if you know of one.

**Comment by damienbod** [comment]
Hi @nigel-dewar 

At present not yet, at present not, my day job is eating up my time. I will get back to you, wanted to start some Electron.

I know of no examples.

Greetings Damien

**Comment by nigel-dewar** [comment]
No probs Damo. Thanks for ur reply.

Nige.


Sent from Samsung Mobile


-------- Original message --------
From: damienbod
Date:18/11/2016 19:36 (GMT+10:00)
To: damienbod/AspNet5IdentityServerAngularImplicitFlow
Cc: nigel-dewar , Mention
Subject: Re: [damienbod/AspNet5IdentityServerAngularImplicitFlow] Any chance can do an Ionic 2 or Electron example? (#34)


Hi @nigel-dewar<https://github.com/nigel-dewar>

At present not yet, at present not, my day job is eating up my time. I will get back to you, wanted to start some Electron.

I know of no examples.

Greetings Damien

-
