### ISSUE TITLE
Compile error in VS 2015

### ISSUE THREAD

**Issue by LiveLikeLastDay** [damienbod/AspNet5IdentityServerAngularImplicitFlow#35]
Severity	Code	Description	Project	File	Line	Suppression State
Error	eqeqeq	Expected '!==' and instead saw '!='.	AngularClient	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\AngularClient\wwwroot\app.js	1	
Error	TS5023	Build:Unknown compiler option 'skipLibCheck'.	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\ResourceWithIdentityServerWithClient.xproj	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\tsc	1	
Error	TS5023	Build:Unknown compiler option 'lib'.	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\ResourceWithIdentityServerWithClient.xproj	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\tsc	1	
Error	TS5023	Build:Unknown compiler option 'types'.	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\ResourceWithIdentityServerWithClient.xproj	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\ResourceWithIdentityServerWithClient\tsc	1	
Error	TS5023	Build:Unknown compiler option 'skipLibCheck'.	Angular2Client	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\Angular2Client\tsc	1	
Error	TS5023	Build:Unknown compiler option 'lib'.	Angular2Client	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\Angular2Client\tsc	1	
Error	TS5023	Build:Unknown compiler option 'types'.	Angular2Client	C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\Angular2Client\tsc	1

**Comment by damienbod** [comment]
Hi @LiveLikeLastDay 

What version of typescript are you using? The first error should only be a warning. Then you should do a npm install from the command line. Some npm libs seem to be missing.

Greetings Damien

**Comment by damienbod** [comment]
Is is ok?, can I close?

**Comment by LiveLikeLastDay** [comment]
Sorry about the delay.

C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\Angular2Client>TSC -V
Version 2.0.3


C:\Git\AspNet5IdentityServerAngularImplicitFlow\src\Angular2Client>npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN webpack-dev-server@1.16.2 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

--------------------------------
I can see lots of folders under Angular2Client\node_modules, but VS 2015 shows that "npm - not installed". The "AngularClient" project looks OK.

Do you think is the related to WebPack as I dodn't setup WebPack?

Yes, you can close it if you can compile, maybe just my enviroment issue.

**Comment by damienbod** [comment]
No this is a VS bug in the tooling. If you do a npm install from the command line it works ok. Scott Hanselman wrote an article about this. Sometimes when npm doesn't work, you need to delete the contents of the npm folder and also the typings and do a npm install from the command line. 

Greetings Damien

**Comment by LiveLikeLastDay** [comment]
Tried delete the contents of the npm folder and run npm install, still same error....

Where is the typings folder/files I need delete?
