### ISSUE TITLE
Update to .NET CORE 1.1

### ISSUE THREAD

**Issue by SamJost** [damienbod/AspNet5IdentityServerAngularImplicitFlow#40]
It would be nice to update the project to use the most recent version 1.1 of ASP.NET Core and the new tools preview.
It might be as little as changing the Version in global.json to "version": "1.0.0-preview2-003131" instead of "version": "1.0.0-preview2-003121"

**Comment by damienbod** [comment]
Hi @SamJost As soon as IdentityServer4 is updated, I will updated. 

Greetings Damien

**Comment by damienbod** [comment]
https://www.nuget.org/packages/IdentityServer4/ rc5

**Comment by damienbod** [comment]
both IdentityServer4 applications updated
TODO:
Client apps and resource servers

**Comment by damienbod** [comment]
completed
