### ISSUE TITLE
Visual Studio 2015 we can't build the project.

### ISSUE THREAD

**Issue by j-nord** [damienbod/AspNet5IdentityServerAngularImplicitFlow#43]
Under Visual Studio 2015 it is not possible to build the project. The build session hangs.

**Comment by damienbod** [comment]
Hi @j-nord 
have you a problem with the restore?

Try from the command line 
$ dotnet restore
$ npm install

If this is ok, then
dotnet build
npm run build-production

Greeetings Damien

**Comment by dev-siberia** [comment]
Problem build and run project **ResourceWithIdentityServerWithClient**. VS 2015 update3.
![default](https://cloud.githubusercontent.com/assets/15089615/22934215/c42a51f2-f300-11e6-8cab-aeb6df4d1016.PNG)

**Comment by damienbod** [comment]
looks like something is wrong with your nodejs and npm
Download the latest version and install
then
$ npm install -g npm@latest 
Go the the project folder

$ npm install
$ npm run build-production

Greetings Damien

**Comment by damienbod** [comment]
VS215 version is now on this branch
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/VS2015_project_json

Have you found out if the client APP builds from the command lien. If it does, then you need to configure the nose stuf in VS2015. If it doesn't build, then you need to install the node stuff

Greetings Damien

**Comment by yhdkzy** [comment]
The first open error
vs2015 update3

=====================
2017/3/16 17:08:25
Crippling
System.AggregateException: 发生一个或多个错误。 ---> System.InvalidOperationException: The source completed without providing data to receive.
   在 System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.InvalidOperationException: The source completed without providing data to receive.
   在 System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.VisualStudio.ProjectSystem.Utilities.Designers.ProjectDataSources.<>c__DisplayClass14_0.<<SyncLinkTo>b__0>d.MoveNext()<---

---> (内部异常 #1) System.InvalidOperationException: 无法将项元数据“%(FullPath)”应用于路径“wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.eot”。D:\work\dl_yhd\project\Demo\guanfang\AspNet5IdentityServerAngularImplicitFlow-VS2015_project_json\AspNet5IdentityServerAngularImplicitFlow-VS2015_project_json\src\IdentityServerWithIdentitySQLite\wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.eot
   在 Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   在 Microsoft.Build.Shared.ErrorUtilities.VerifyThrowInvalidOperation(Boolean condition, String resourceName, Object arg0, Object arg1, Object arg2)
   在 Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath)
   在 Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath)
   在 Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name)
   在 Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
   在 Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
   在 Microsoft.VisualStudio.ProjectSystem.ProjectInstanceItemProperties.GetEvaluatedPropertyValueAsync(String propertyName)
   在 Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageRuleBase.GetPropertyValueAsync(String propertyName)
   在 Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.GetItemMetadata(IImmutableDictionary`2 basis, IRule rule)
   在 Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildItemsSnapshot(IRule rule, IProjectCatalogSnapshot projectCatalogSnapshot, ImmutableDictionary`2 previousVersion, ImmutableList`1 recentItemRenames, ImmutableHashSet`1& addedItems, ImmutableHashSet`1& removedItems, ImmutableHashSet`1& changedItems, ImmutableDictionary`2& renamedItems)
   在 Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.UpdateRuleSnapshotCore(IProjectVersionedValue`1 source, String ruleName, IRule rule, ImmutableDictionary`2 items, ImmutableDictionary`2 properties, ImmutableList`1 recentItemRenames, IProjectChangeDiff& diff)
   在 Microsoft.VisualStudio.ProjectSystem.Designers.ProjectRuleSubscriptionServiceBase`1.UpdateSnapshotCoreAsync(TSource source, IImmutableSet`1 subscribedElements, IProjectVersionedValue`1 previousResult)
   在 Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<UpdateSnapshotAsync>d__28.MoveNext()

![qq 20170316170916](https://cloud.githubusercontent.com/assets/1321058/23989865/17194ac8-0a6f-11e7-87de-0178337ff5dd.png)
![qq 20170316173839](https://cloud.githubusercontent.com/assets/1321058/23989977/75c745ca-0a6f-11e7-87a6-1a362aa48af2.png)

**Comment by damienbod** [comment]
Hi @yhdkzy You can't build the Angular2Client project, correct?
try from the command line as a test.
Change to the project directory and delete everything from the node_modules folder
> npm install
> npm run build-production
> dotnet restore
> dotnet build

Greetings Damien

**Comment by yhdkzy** [comment]
Hi @damienbod , i can build now. How do I run and test? I am a novice. Thanks

**Comment by damienbod** [comment]
2 ways. From the console
>npm install
>npm run build-production
>dotnet restore
>dotnet run

If this works then you can try from VS, problem here is that the wrong Node.js version is used per default. You need to use the node.js installed directly and not that from VS.

Greetings Damien

**Comment by dgouissem** [comment]
Hello,
I'm getting below error when trying to start all the projects in the solution thru the run IIS Express commande in VS 2017:
unable to connect to web server iis express 

Any clues to resolve this issue,

Thank you

**Comment by damienbod** [comment]
closing this, please reopen if it is stillan issue
