### ISSUE TITLE
Angular 2 + MVC ?

### ISSUE THREAD

**Issue by kuncevic** [damienbod/AspNet5IdentityServerAngularImplicitFlow#44]
Your example `AngularClient` is sort of mixture MVC + Angular 2 is there reason for that? 
Why wouldn't you use just Angular-CLI for that project ?

**Comment by damienbod** [comment]
Hi @kuncevic It's just just the MVC for the WebAPI (service on the server). The Angular app is in the same project, which makes it easier to deploy, in some scenerios. Angular-CLI would be  a good solution, if you split the apps into 2 projects. Angular-CLI comes with a lot of overhead, and doesn't update so good. I prefer just an angular app with a webpack build but it's just a preference.

Greetings Damien
