### ISSUE TITLE
PostLogoutRedirectUri  is null

### ISSUE THREAD

**Issue by elciopa** [damienbod/AspNet5IdentityServerAngularImplicitFlow#45]
Hi,
first of all thanks for the work you're doing. I'm really appreciating these examples cause they're giving me a way to start my implementation. I started from your IdentityServerWithIdentitySQLite project and used SQLServer instead of SQLite. Everything is working, I have many clients and I would say everything is ok except for one issue: PostLogoutRedictUris are always null, so there's no redirection once the user accept to logout. 

From the OpenId Connect protocol I know that logout should do a get request to the IdentityServer4:
`/connect/endsession?id_token_hint=...&post_logout_redirect_uri=https://myapp.com`
as written here in the documentation https://identityserver.github.io/Documentation/docsv2/endpoints/endSession.html. 

By debugging I saw that the IdentityServer automatically redirect this request (302 http code) to
`/account/logout?logoutId=0cf0260b9525018e49bb0e9398691865` and then your AccountController.cs take the request and should get info about the LogoutId using the `IIdentityServerInteractionService _interaction `variable. Here is my issue:

```
var logout = await _interaction.GetLogoutContextAsync(model.LogoutId);
var vm = new LoggedOutViewModel
            {
                PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
                ClientName = logout?.ClientId,
                SignOutIframeUrl = logout?.SignOutIFrameUrl
            };
```
`logout` has all fields sets to null, except for the SignOutIframeUrl which is set to the url of the http://identityserverurlandport//connect/endsession/callback?sid=e9dd3bdacab365f7fd1872f3ddfb2852&logoutId=0cf0260b9525018e49bb0e9398691865

Do you have an idea why _interaction is not giving me any information from my LogoutId? LogoutId as you can see is not empty. I really do not catch why GetLogoutContextAsync is giving me back null values except SignOutIframeUrl.

Alessandro

**Comment by damienbod** [comment]
@elciopa thanks, I'l have  a look, 

Greetings Damien

**Comment by damienbod** [comment]
Hi @elciopa Just checked this and it's working, can I close?

Greetings Damien

**Comment by elciopa** [comment]
yes at the end I'm able to do the postlogout redirect correctly. You can close it!
Thanks
