### ISSUE TITLE
Use Identity with IdentityServer4

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#5]

**Comment by mabouchalkha** [comment]
do you have any idea how to implement that

**Comment by damienbod** [comment]
Hi @mabouchalkha 

IdentityServer4 support for Identity is not ready yet. This will be implemented some time after the ASP.NET Core RC2 release. Then the new interfaces to implement identity will be available. 

Greetings Damien

**Comment by damienbod** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/SpaWithAspId3AndIdSvr4

**Comment by mabouchalkha** [comment]
thanks a lot

**Comment by damienbod** [comment]
implemented
