### ISSUE TITLE
sessionStorage is not defined

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#50]
I implemented angular2client oidc service, when I run app in .net core I get following error:

> An unhandled exception occurred while processing the request.
> 
> Exception: Call to Node module failed with error: ReferenceError: sessionStorage is not defined
> at new OidcSecurityService

**Comment by damienbod** [comment]
The sessionStorage is used here
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.service.ts#L273
and set in the ctor. 

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.service.ts#L35

Setup a breakpoint to test in your app.

Greetings Damien

**Comment by nukec** [comment]
damien I understand that, I used your code to implement oidc service, and I am using it with "dotnet new angular" using visual studio 2017 template from this url: https://jonhilton.net/2017/02/21/create-a-vs2017-angular-2-and-net-core-site-using-the-command-line/ . Once I put this inside it works first time, then when i rebuild, it gives that error.

**Comment by nukec** [comment]
Ok this is resolved by putting if(isBrowser) for window, sessionStorage and getItem.

**Comment by damienbod** [comment]
thanks for the fix, will add it.
