### ISSUE TITLE
angularJS client - This is server routing, not angular2 routing??? where is the index page?

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#51]
Hi Damo,

With the angularJS client, loading just says This is server routing, not angular2 routing

Looking in the project, there is no index page either? something missing here?

Cheers

**Comment by damienbod** [comment]
Hi @nigel-dewar 
I'll have a look, have checked this in a while, been focusing on angular 2/4 later

Greetings Damien

**Comment by nigel-dewar** [comment]
No worries mate. I know everyone has moved onto ng2. But just thought id ask because i testedthis and the result didnt make sense to me. Cheers

**Comment by damienbod** [comment]
@nigel-dewar I've updated the angularjs client and tested it now. Should work, you might need to build the angularjs client first before starting (grunt default build in the task runner)

Greetings Damien

**Comment by nigel-dewar** [comment]
Thanks Damo ill check it out. Hey one question, Did you ever go down the path of embedding the angular app in an mvc page? And use SpaServices to fix the mvc and angular routes? I ask becuase im working out pros and cons of this method.

**Comment by damienbod** [comment]
yes you could also do the client sever routing like this:

https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/

Using Angular in a MVC page  works with the lose of some angular features. You should use the angular features lazy loading, AOT and tree shaking. Splitting the app using angular modules and lazy loading gives a really good user experience.

Greetings Damien
