### ISSUE TITLE
KEYUTIL is not defined

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#52]
So I got authorization with IdentityServer4 working(get id_token, access_token etc), but after authorization is done I get this error:

> EXCEPTION: KEYUTIL is not defined
> ErrorHandler.handleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:78735
> next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:53403
> schedulerFn @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:55466
> SafeSubscriber.__tryOrUnsub @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21253
> SafeSubscriber.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21202
> Subscriber._next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21144
> Subscriber.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21108
> Subject.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:46531
> EventEmitter.emit @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:55452
> NgZone.triggerError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:44947
> onHandleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:44908
> ZoneDelegate.handleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66745
> Zone.runTask @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66576
> ZoneTask.invoke @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66827
> vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:78740 ORIGINAL STACKTRACE:
> ErrorHandler.handleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:78740
> next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:53403
> schedulerFn @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:55466
> SafeSubscriber.__tryOrUnsub @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21253
> SafeSubscriber.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21202
> Subscriber._next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21144
> Subscriber.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:21108
> Subject.next @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:46531
> EventEmitter.emit @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:55452
> NgZone.triggerError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:44947
> onHandleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:44908
> ZoneDelegate.handleError @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66745
> Zone.runTask @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66576
> ZoneTask.invoke @ vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:66827
> vendor.js?v=zXjAceTbWZzNTMXFaXt8RHn0kEuzf0rVAtRzIJqw-9Q:78741 ReferenceError: KEYUTIL is not defined
>     at OidcSecurityValidation.Validate_signature_id_token (http://localhost:5000/dist/main-client.js?v=lgL9VcwhhuqUxAGEZD3Bu1eVNir5kB4ni5zzLZqiCc8:2470:33)

KEYUTIL is in oidc.security.validate.ts. I read that this is in jrsasign, but I am not sure you used this library in package.json?

**Comment by damienbod** [comment]
I had problems using this from the npm package so I added this in the assets and ref it from the index.html.

**Comment by nukec** [comment]
@damienbod brilliant, i didn't see it, it's working now. by the way, what was the issue with npm, i tried to install it as well, but it was not recognizing it inside.

PS: i forked your project for another bug, and tried to commit, but i don't have access:

> remote: Permission to damienbod/AspNet5IdentityServerAngularImplicitFlow.git denied to nukec.
> fatal: unable to access 'https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow.git/': The requested URL returned error: 403

**Comment by damienbod** [comment]
Cool thanks, did a blog about this:
https://damienbod.com/2016/11/25/contributing-to-oss-projects-on-github-using-fork-and-upstreams/
just create a pull request

Thanks Damien
