### ISSUE TITLE
EnablePostSignOutAutoRedirect in angular2 client

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#53]
How to implement EnablePostSignOutAutoRedirect or any other options like EnableSignOutPrompt for identityserver in angular client? 

I read what is required here: https://github.com/IdentityServer/IdentityServer3/issues/1121 but not sure where in your service implementation should i inject these properties?

**Comment by damienbod** [comment]
Hi @nukec  In the logoff function:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.service.ts#L212

The post_logout_redirect_uri is passed here as a parameter.

Greetings Damien
