### ISSUE TITLE
permission to reference your work.

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#55]
Gday Damo. Your work is amazing. I've got some work i want to share with the breezejs guys, and I'm using angular2 with code referenced from you . Just wanted to check if it's ok to share your identityserver4 angular2 setup? All credit will be given to yourself of couse.

**Comment by damienbod** [comment]
of course, delighted you can use it, thanks

Greetings Damien

**Comment by nigel-dewar** [comment]
Thanks Damo appreciate that!

Just for my info, did you ever build in a 'token expiring' function to automatically renew tokens ? Just asking in case i need to program this .

cheers

**Comment by damienbod** [comment]
No, need to implement this, I'm planning on implementing the OpenID session management next.

Greetings Damien

**Comment by nigel-dewar** [comment]
Oh cool that sounds really good. 

Ill have a crack at tokenexpiring at my end and let u know how i go

Look forward to seeing how u go with openid session management

cheers
