### ISSUE TITLE
Question: Have you had success using angular2-jwt from Auth0 for angular client?

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#56]
Hi Damo,

Just looking at this sample https://github.com/robisim74/AngularSPAWebAPI from Roberto Simonetti.

Hes using angular2-jwt to do a resource owner password creds signin. 

Have you had any success using angular2-jwt to do implicit flow with your work?

Cheers

**Comment by damienbod** [comment]
Hi @nigel-dewar 
No, I don't need this as I have to validate the token and so need a security library for this which does everything that library does.

Greetings Damien
