### ISSUE TITLE
Identity roles with angular 2 implicit client

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#57]
I've implemented access for logged users with CanActivate, I am interested how to limit some areas only to admin user with your approach? When oidc checks if user is real, how do I retrieve role of user and store it in local storage? Do you have an example of this? What could be an approach? I am using identityserver4 and asp.net core identity integration to query with database users.

My architecture is as follows: Angular 2 client -> IdentityServer4 -> Web.Api which is protected by IdentityServer4. This web api has an endpoints

**Comment by damienbod** [comment]
Hi @nukec 
You can add extra claims to the tokens using the IProfileService interface.

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/IdentityServerWithIdentitySQLite/IdentityWithAdditionalClaimsProfileService.cs

Or you can query the User API to get the user details from the database. You should keep the tokens small.

Greetings Damien

**Comment by Brammii** [comment]
Hi Damien,

In your all-in-1 project “ResourceWithIdentityServerWithClient” you have created a UserManagementController. Where should we put that controller if we use the separated projects? Is it ok to use it on the identityserver? Or should we create a special authorization/permission server (microservice)?

Dominick Baier told on his blog https://leastprivilege.com/2016/12/16/identity-vs-permissions/
that IdentityServer is not so well suited for letting clients or APIs know what a user is allowed to do – e.g. create a customer record, delete a table, read a certain document etc…
He also told: 
> “Design for a clean separation of identity and permissions. Acquire authorization data as close as possible to the code that needs it – only there you can make an informed decision what you really need.”
“If you realize that the number of roles of a user is high – or growing – avoid putting them into the token.”

 
Like you said: keep your token small. But could you give us an example of separation of identity and permissions ;-)?

**Comment by nukec** [comment]
@Brammii that's what I am thinking. I think only Login should be there to actually check against database user, and remove everything else, and implement registration on private api.

**Comment by damienbod** [comment]
@Brammii 
The IdentityServer4 is just an ASP.NET Core application. The application could be extended to implemented this. If your not used Identity in IdentityServer4 but an external login, then the external login source would be the best place for this.

**Comment by nukec** [comment]
You mean to publish identity login endpoint on other webapp and do post request from identity server 4? is there any specific example of that?

**Comment by damienbod** [comment]
user info has it's own service
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.user-service.ts
