### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by garkuwa** [damienbod/AspNet5IdentityServerAngularImplicitFlow#58]
Hi,
I wondered if there is any logic for refresh/inactivate of tokens. Maybe I just didn't find code for this or its out of scope? Thank you.

Best regards,
Taras Pysarskyi

**Comment by damienbod** [comment]
no, haven't implemented anything like this.

Here's an example with ROPC
https://github.com/robisim74/AngularSPAWebAPI

Greetings Damien

**Comment by garkuwa** [comment]
Thanks a lot for reply and example reference.

Regards, Taras
