### ISSUE TITLE
Is the AngularJSClient missing all the html files?

### ISSUE THREAD

**Issue by MagnusJohansson** [damienbod/AspNet5IdentityServerAngularImplicitFlow#59]
Is it just me, or is the AngularJSClient project missing all the .html files?
(such as index.html, /templates/...  etc)

**Comment by damienbod** [comment]
yes, sorry

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/AngularJSClient/wwwroot/templates

Greetings Damien
