### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by mabouchalkha** [damienbod/AspNet5IdentityServerAngularImplicitFlow#6]
hi,
Thanks a lot for your sample very helpful.
i've got error when i click to login? i don't know why.
i've got the same error when i use implicit flow example here https://github.com/IdentityServer/IdentityServer4.Samples 

can you please help.

<img width="789" alt="error" src="https://cloud.githubusercontent.com/assets/4623561/12378056/2cc8ba74-bd00-11e5-90b1-c8ee72d51383.PNG">

**Comment by mabouchalkha** [comment]
I think is the same https://github.com/IdentityServer/IdentityServer4/issues/15 and https://github.com/aspnet/HttpAbstractions/issues/535
thank you

**Comment by damienbod** [comment]
Hi @mabouchalkha 

Sorry for the slow answer. I'll have a look next week, have to complete a project before Monday, and have no time till then.

greetings Damien

**Comment by mabouchalkha** [comment]
No problem thanks

**Comment by damienbod** [comment]
Hi @mabouchalkha, have you figured out your problem yet. If not could you post some more details, client, Startup configuration, login url etc

I'll have a look. Does the example as it is, work for you? You might have to fix the port numbers locally.

Greetings Damien

**Comment by damienbod** [comment]
Hi @mabouchalkha, I also received this user, when I defined my Users and Clients incorrectly, copy pastes errors.

Maybe this helps

Greetings Damien

**Comment by mabouchalkha** [comment]
yes thank you my problem is the same like IdentityServer/IdentityServer4#15 and aspnet/HttpAbstractions#535 i have to clear ly cookies and it works thank you
