### ISSUE TITLE
Problem testing solution

### ISSUE THREAD

**Issue by Looooooka** [damienbod/AspNet5IdentityServerAngularImplicitFlow#60]
Started identityserver using dotnet run command.
works...can register and login no problem.
I did the same with the angularjs project
and when I click login(which redirects to https://localhost:44318/connect/authorize?response_type=id_token%20token&client_id=angularclient&redirect_uri=https://localhost:44311&scope=dataEventRecords%20securedFiles%20openid&nonce=N0.67227080542520781494324578419&state=14943245784190.2680971994084269)
in identityserver console window(dotnet run) I can see the following error:

info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HL4MOEREIUJ5" bad request data: "Invalid request line: <0x16><0x03><0x03><0x00><0xC9><0x01><0x00><0x00><0xC5><0x03><0x03>Y<0x11><0x95><0xBD><0xD6><0xC1><0xC5>::<0xE9>O<0x87><0x9D><0x80><0x98>L<0xAC>"<0xA6><0x91><0x1B>..."
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x03><0x00><0xC9><0x01><0x00><0x00><0xC5><0x03><0x03>Y<0x11><0x95><0xBD><0xD6><0xC1><0xC5>::<0xE9>O<0x87><0x9D><0x80><0x98>L<0xAC>"<0xA6><0x91><0x1B>...
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HL4MOEREIUJ6" bad request data: "Invalid request line: <0x16><0x03><0x01><0x00><0x83><0x01><0x00><0x00><0x7F><0x03><0x01>Y<0x11><0x95><0xBD>e<0x9A><0x09>k<0xF9>iH<0xE7>O<0x05><0x18><0x8F><0x7F>fe<0x14>%..."
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x01><0x00><0x83><0x01><0x00><0x00><0x7F><0x03><0x01>Y<0x11><0x95><0xBD>e<0x9A><0x09>k<0xF9>iH<0xE7>O<0x05><0x18><0x8F><0x7F>fe<0x14>%...

any idea on how to fix this?

**Comment by Looooooka** [comment]
Never mind...using ctrl +F5 and running both project that way seems to generate a warning about the authenticity of the certificate but at least then it gives you the options of opening the page and the redirect actually works

**Comment by damienbod** [comment]
I need to document this, thanks

**Comment by PivotalAnimal** [comment]
This link might help: https://stackoverflow.com/questions/43676993/how-do-i-change-my-iis-express-ssl-certificate-for-one-that-will-work-with-chrom

I have that problem solved but am now getting runtime errors:

polyfills.3afc0ffb2b25dfd149b9.bundle.js:1 Uncaught SyntaxError: Unexpected identifier
vendor.3afc0ffb2b25dfd149b9.bundle.js:1 Uncaught SyntaxError: Unexpected identifier
app.3afc0ffb2b25dfd149b9.bundle.js:1 Uncaught SyntaxError: Unexpected identifier

I think it might have to do with the way the bundles are referenced:
`<script type="text/javascript" src="/dist/polyfills.3afc0ffb2b25dfd149b9.bundle.js"></script><script type="text/javascript" src="/dist/vendor.3afc0ffb2b25dfd149b9.bundle.js"></script><script type="text/javascript" src="/dist/app.3afc0ffb2b25dfd149b9.bundle.js"></script>`


@leastprivilage, you might want to consider using JavaScriptServices SPA template. It creates very clean code that runs no problem for me:
`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>

<script src="~/dist/vendor.js" asp-append-version="true"></script>
@section scripts {
    <script src="~/dist/main-client.js" asp-append-version="true"></script>
}`

I am going through the tutorial now:

https://channel9.msdn.com/Events/Visual-Studio/Visual-Studio-2017-Launch/WEB-103

Building SPA Applications on ASP.NET Core with JavaScriptServices
https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/

https://github.com/aspnet/JavaScriptServices

**Comment by damienbod** [comment]
@PivotalAnimal  you just need to build the client stuff and maybe configure VS2017 to use the proper node. The client build supports AOT production builds and client lazy loading.

See this solution for help in building

https://github.com/damienbod/AngularWebpackVisualStudio

Greetings Damien

**Comment by PivotalAnimal** [comment]
Hi Damiean,

I've made some progress. The sites are all building and running. However, I am now receiving the following error when trying to register a user:
`Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String c
ontextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
SQLite Error 14: 'unable to open database file'.`

Do you have any idea what the problem might be? I've done some research but haven't yet been able to figure this out. I was able to successfully run the following example: https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite

Thanks,

Kai

**Comment by damienbod** [comment]
Hi @PivotalAnimal The path for the sqlite database is configured here:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/IdentityServerWithIdentitySQLite/appsettings.json

You need to change this to match yours. If you created a new database,  you need to create it, for example using EF Core migrations.

Greetings Damien

**Comment by PivotalAnimal** [comment]
HI @damienbod, the SQLite problem is fixed. Now I am attempting to fix the following:

> GET https://localhost:44390/api/DataEventRecords/ 500 ()
:44311/dataeventrecords/list:1 XMLHttpRequest cannot load https://localhost:44390/api/DataEventRecords/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44311' is therefore not allowed access. The response had HTTP status code 500.

Thanks,

Kai

**Comment by damienbod** [comment]
This is strange, seems like the CORS configuration is missing

**Comment by PivotalAnimal** [comment]
I turned on developer exceptions and found the cause. Even though my AV was allowing the CERT I had generated previously, I forgot to add it to the trusted root. Now Chrome is happy and so am I. Thanks again!
