### ISSUE TITLE
All in one project will not allow external providers like Google

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#61]
Hi Damo, 

with your all in one project, 'the project with idserver, api and everything combined', have you tried adding an external provider like google?

I think you will find it wont work. I have tried it myself on my project, following your solution code, and it does not work for me.

**Comment by damienbod** [comment]
Should work, I have deleted all the views, controller stuff required, otherwise there is nothing special with the all in one solution apart from that.

Greetings Damien

**Comment by nigel-dewar** [comment]
I found I had to remove this. for some reason no external auth for me happens whilst its in startup file


JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();




________________________________
