### ISSUE TITLE
Auto login after registration

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#64]
Damien thanks for previous answers. Helped a lot. I am wondering if there is a way with implicit flow to auto login user after registration of new user has been done? Or do I have to user other grant type like credentials which is less secure?

**Comment by damienbod** [comment]
Hi @nukec don't quite understand what you want. auto login should be possible.

**Comment by nukec** [comment]
When I register account I would like to auto login. Is there any implementation with angular2 your example, with identity server 4 implicit flow?

**Comment by damienbod** [comment]
The all in one solution should do this, must check. You need to change the controllers on the server

**Comment by nukec** [comment]
Any info on this?

**Comment by damienbod** [comment]
This should work.

Greetings Damien

**Comment by nukec** [comment]
@damienbod any example of how to enable this to work?
