### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by curlyfro** [damienbod/AspNet5IdentityServerAngularImplicitFlow#7]
can you show an example of this using Angular2?

[http://stackoverflow.com/questions/35048005/has-anyone-created-any-angular2-auth-wrapper-classes-for-identityserver-3-4](http://stackoverflow.com/questions/35048005/has-anyone-created-any-angular2-auth-wrapper-classes-for-identityserver-3-4)

**Comment by damienbod** [comment]
Sounds like a good idea, I'm learning it now.

**Comment by curlyfro** [comment]
this is what i've got so far...  maybe you can find something in here useful.

[gist:https://gist.github.com/curlyfro](https://gist.github.com/curlyfro)

**Comment by damienbod** [comment]
cool thanks

**Comment by damienbod** [comment]
TODO: error handling 401, 403

**Comment by damienbod** [comment]
@curlyfro  Angular2 client is implemented, greetings Damien
