### ISSUE TITLE
Did you manage to get oidc session management running?

### ISSUE THREAD

**Issue by nigel-dewar** [damienbod/AspNet5IdentityServerAngularImplicitFlow#72]
Hi Damo,

Did you manage to get oidc session management up and running? So that there are token refresh etc? silent token refresh, that sort of thing?

Cheers
Nige

**Comment by damienbod** [comment]
Yes, the tokens are updated when the id_token expires

https://damienbod.com/2017/06/02/implementing-a-silent-token-renew-in-angular-for-the-openid-connect-implicit-flow/

Greetings Damien

**Comment by nigel-dewar** [comment]
Oh epic Damo, you're then Man!!!

Cheers mate ill check it out!

Thanks for all ur hard work!


Sent from Samsung Mobile


-------- Original message --------
From: damienbod
Date:07/06/2017 14:16 (GMT+10:00)
To: damienbod/AspNet5IdentityServerAngularImplicitFlow
Cc: nigel-dewar , Author
Subject: Re: [damienbod/AspNet5IdentityServerAngularImplicitFlow] Did you manage to get oidc session management running? (#72)


Yes, the tokens are updated when the id_token expires

https://damienbod.com/2017/06/02/implementing-a-silent-token-renew-in-angular-for-the-openid-connect-implicit-flow/

Greetings Damien
