### ISSUE TITLE
Question: is there a specific reason why you use Sqlite and not localdb?

### ISSUE THREAD

**Issue by paulvanbladel** [damienbod/AspNet5IdentityServerAngularImplicitFlow#76]
Very nice sample Damien.
Is there a specific reason why you use Sqlite and not localdb?

**Comment by damienbod** [comment]
Thanks, no specifc reason, I like SQLite and wanted to try it out. I was considering this for a MC security solution, where max 10 exists and only 1 operator at a time.

**Comment by paulvanbladel** [comment]
Cool. I just saw your excellent post about sqlite https://damienbod.com/2015/08/30/asp-net-5-with-sqlite-and-entity-framework-7/

I was looking for a db (which might be small in size) which should run both on linux and windows. As far as I can see localdb won't work on linux. Sqlite does. On the other hand, localdb has excellent EF migrations support.  Sqlite has EF migrations limitations.
https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations.
