### ISSUE TITLE
Problem with page refresh

### ISSUE THREAD

**Issue by dev-siberia** [damienbod/AspNet5IdentityServerAngularImplicitFlow#77]
Project: ResourceWithIdentityServerWithClient.
After updating the page, the authorization data is deleted in the browser.
Console message: User must be logged in before you can get the user data!
Please help my.

**Comment by damienbod** [comment]
Hi @dev-siberia  seems to be something wrong with the server routing, I'll have a look.

**Comment by dev-siberia** [comment]
Hi @damienbod! 
I found one solution. UserData was not saved in the SessionStorage. Added the SetUserData method to the file oidc.security.service.ts

 ```
private setUserData(userdata: any) {
     this.oidcSecurityCommon.store(this.oidcSecurityCommon.storage_user_data, userdata);
}
```
```
171 if (authResponseIsValid) {
...
181 this.oidcSecurityCommon.logDebug(this.oidcSecurityUserService.userData);
183 -> this.setUserData(this.oidcSecurityUserService.userData);
```
index.html file modify <base href="./"> to <base href="/">

navigation.component.ts method load add if (userData) {

```
if (userData) {
      for (let i = 0; i < userData.role.length; i++) {
            if (userData.role[i] === 'dataEventRecords.admin') {
                  this.hasDataEventRecordsAdminRole = true;
             }
              if (userData.role[i] === 'admin') {
                    this.hasAdminRole = true;
              }
       } 
 } 
```

and modify constructor
```
constructor(
    public securityService: OidcSecurityService
) {
    this.securityService.onUserDataLoaded.subscribe(() => { this.load(); });
    this.load();
}
```

And it works) Now I can refresh the page as many times as I want.

**Comment by chinkan** [comment]
I had that issue also, I just modify oidc.security.user-services.ts:
```
initUserData() {
        return this.getIdentityUserData()
            .map(data => {
                this.userData = data;
                this.oidcSecurityCommon.store(this.oidcSecurityCommon.storage_user_data, this.userData)
            });
    }
```
and it work now.

**Comment by damienbod** [comment]
fixed:
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/AngularClient/angularApp/app/auth
