### ISSUE TITLE
Can I use this library with CanActivate Guard?

### ISSUE THREAD

**Issue by chinkan** [damienbod/AspNet5IdentityServerAngularImplicitFlow#78]
I am writing a asp.net core application with angular. I just use CanActivate to keep away the unauthorized user to the protected page. Here is my code:

```
import { Injectable } from '@angular/core';
import { CanActivate } from '@angular/router';
import { OidcSecurityService } from '../auth/services/oidc.security.service';

@Injectable()
export class CanActivateGuard implements CanActivate {

    constructor(
        private securityService: OidcSecurityService
    ) {
    }

    public canActivate() {
        // test here if you user is logged
        var connected = this.isConnected();
        console.log("canActivate", connected);
        if (!connected) {
            this.securityService.authorize();
        }
        return connected;
    }

    private isConnected(): boolean {
        let user = this.securityService.getUserData();
        return null != user;
    }
}
```

However, the function `this.securityService.getUserData();` always return null even user has logged to the identityserver. How could I use the CanActivate with identityserver? Thanks!

Sorry for my English!

**Comment by damienbod** [comment]
@chinkan hi you could used te userdata event. The user data is only returned after a server request. Until then, no data is returned. The event is called after a successfully authorization callback. 

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/oidc.security.service.ts#L20

You should call the  this.securityService.authorize(); in a login component and call the authorizationCallback where the successful login is redirected. The guards should use the isAuthorised property.

Greetings Damien

**Comment by chinkan** [comment]
Hi @damienbod, Thanks for your reply, could I done this without login component. I want to the the application which must be login show that I want to make the application auto redirect to the identityserver if user logged in or show the login form from identityserver. User thus no need to click login button for logging in to the system. Thanks again!

**Comment by damienbod** [comment]
No problem as long as you handle the authoriseCallback. Once this is ok, the userData is requested from the server. After the response, the userData function returns data. The event is triggered on a response event.

**Comment by chinkan** [comment]
Hi @damienbod , Just follow your instruction, I have updated the grand.services.ts to this

```
import { Injectable } from '@angular/core';
import { CanActivate } from '@angular/router';
import { OidcSecurityService } from '../auth/services/oidc.security.service';

@Injectable()
export class CanActivateGuard implements CanActivate {

    constructor(
        private securityService: OidcSecurityService
    ) {
    }

    public canActivate() {
        return this.securityService.isAuthorized;
    }
}
```
and I then added `this.securityService.authorizedCallback();` and `this.securityService.authorize();` to app.component.ts like this:

```
import { Component, OnInit } from '@angular/core';
import { OidcSecurityService } from './auth/services/oidc.security.service';

@Component( {
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
    constructor(
        private securityService: OidcSecurityService
    ) {

        securityService.onUserDataLoaded.subscribe((r) => {
            console.log("user data loaded.", r);
        }, (e) => {
            console.log("user data error.", e);
        }, () => {
            console.log("user data ended.");
        });

        if (!this.securityService.isAuthorized) {
            this.securityService.authorize();
        }
    }

    public ngOnInit() {
        console.log('AppComponent');
        if (window.location.hash) {
            this.securityService.authorizedCallback();
        }
    }
}
```

It can show the login form in the first time, however it will keep redirect after submit the login form.
Also I had subscribed the onUserDataLoaded event but nothing call in it. What is my fault in my code?

Thanks for your help!

**Comment by chinkan** [comment]
Hi @damienbod ,

I have solved the issue, just put the `this.securityService.authorize();` to the else case of `if (window.location.hash)` and work perfectly! Many thanks for your help and have a nice day! :)

```
import { Component, OnInit } from '@angular/core';
import { OidcSecurityService } from './auth/services/oidc.security.service';

@Component( {
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
    constructor(
        private securityService: OidcSecurityService
    ) {

        securityService.onUserDataLoaded.subscribe((r) => {
            console.log("user data loaded.", r);
        }, (e) => {
            console.log("user data error.", e);
        }, () => {
            console.log("user data ended.");
        });
        
    }

    public ngOnInit() {
        console.log('AppComponent');
        if (window.location.hash) {
            this.securityService.authorizedCallback();
        }
        else {
            if (!this.securityService.isAuthorized) {
                this.securityService.authorize();
            }
        }
    }
}
```

**Comment by chinkan** [comment]
Oh, just a bit try, I sometimes got the url to be "undefined?response_type=id_token%20token&client_id=" at the function createAuthorizeUrl in oidc.security.service.ts when I call `this.securityService.authorizedCallback();
`, It seem to be auth well known endpoint not yet loaded and the authorization_endpoint become undefined. How can I prevent this issue? Thanks!

**Comment by damienbod** [comment]
The discovery is loaded when then AuthWellKnownEndpoints constructor is call, round trip. Until this is finished, the urls are not available. I'll add a check for this.  If your using the src code, you could add this to the AuthWellKnownEndpoints  class and use it before you call the authorize function. 

I'll fix this, this week. Thanks for reporting.

**Comment by chinkan** [comment]
Hi @damienbod , Thanks for your help! I just added onWellKnownEndpointLoaded EventEmitter and also add a isLoading flag in AuthWellKnownEndpoints to ensure it finished loading. But I don't know whether this modify is good or not. I will waiting for your updates. Thanks again for your help and have a nice day! :)

**Comment by damienbod** [comment]
OK, I'll try to do it today

**Comment by damienbod** [comment]
@chinkan This now works, you can user the event 
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/auth/services/auth.well-known-endpoints.ts#L15

Greetings Damien

**Comment by damienbod** [comment]
yes

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/ResourceWithIdentityServerWithClient/angularApp/app/guards/hasAdminRoleAuthenticationGuard.ts
