### ISSUE TITLE
oidc silent-renewal and check-session stop after page refresh

### ISSUE THREAD

**Issue by InDieTasten** [damienbod/AspNet5IdentityServerAngularImplicitFlow#79]
The `oidc.security.silent-renew.ts` and `oidc.security.check-session` initializers are called only from authorization callback. But we store authorization data in local storage, so when we refresh, we don't want to do a roundtrip using `authorize()` just so those two iframes are created again.

I've got a messy workaround for both problems now, but this really seems like a flaw in the current implementation. It should be able to continue checking the session and renew tokens, even if the page is being refreshed and all the authorization data comes from local storage.

Solution:
On construction of both these services, check if the the state of the oidc authorization data `isAUthorized` is truthy, and initialize both timers.

**Comment by damienbod** [comment]
thanks, will fix, also have a separate bug opened for this

**Comment by damienbod** [comment]
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/issues/77

**Comment by damienbod** [comment]
@InDieTasten thanks for the issues, if you want to fix any of these, I accept pull requests and would be very grateful. Otherwise I will do it as soon as I get time. 

Also, all fixes here get added to the npm lib:

 https://github.com/damienbod/angular-auth-oidc-client

If you want, you can get involved. 

Greetings Damien

**Comment by InDieTasten** [comment]
@damienbod I will have to ask my manager, whether I'm allowed to invest time into that. I will inform you about that decision once it's done.

Greetings Max

**Comment by InDieTasten** [comment]
Ok, it's now very likely that my company is going to open an organization account here on GitHub. It will take some time though until I am actually allowed to start working on this.

Regards

**Comment by damienbod** [comment]
@InDieTasten This has been refactored now, the iframe are no longer only called, or called many times in the auth calback. Still longs the whole app though

**Comment by damienbod** [comment]
fixed 
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/AngularClient/angularApp/app/auth
