### ISSUE TITLE
oidc silent-renew unnecessary decoding of tokens in loop

### ISSUE THREAD

**Issue by InDieTasten** [damienbod/AspNet5IdentityServerAngularImplicitFlow#80]
Current implementation of the silent-renew decodes the id_token every 3 seconds to parse the expiration claim and check it against the clock to see, if we have to silently renew the token with our iframe.

Why don't we parse the id_token expiration once, and set a timeout to exactly a configurable number of seconds before expiry?

Then we only decode it once, we have one fewer 3 second loop, and we also have better control over when we actually want to renew the token

**Comment by damienbod** [comment]
good idea, 

Also I would renew only every 5 minutes
