### ISSUE TITLE
oidc silent-renew only checks for id_token

### ISSUE THREAD

**Issue by InDieTasten** [damienbod/AspNet5IdentityServerAngularImplicitFlow#81]
In the current implementation, the silent-renew only checks the expiration of the id_token, which might have a significantly greater lifetime than access_tokens. The silent-renew should renew in cases of either of them running out of lifetime. This way, the RP can ensure, that they always have a valid id_token AND a valid access_token.

**Comment by InDieTasten** [comment]
For renewing the access_token while we have a valid id_token, the implementation should also include `prompt=none&id_token_hint=...` to gather new access tokens?

**Comment by damienbod** [comment]
doesn't need this, but it should be possible

**Comment by damienbod** [comment]
This is now possible with the custom params in the authorize URL. The access_token is validated as per OIDC. The resource server validates the access_token.

**Comment by InDieTasten** [comment]
Did you already update this repository? According to https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/d2b09394895328e6c7a6c02a1eb98d5309dc774d/src/AngularClientIdTokenOnly/angularApp/app/auth/services/oidc.security.service.ts#L492

there still is no check for the access_token to have expired.

**Comment by damienbod** [comment]
Hi @InDieTasten The client API validates that the access_token is valid using the id_token (not expired). The access_token is onl required by the APIs, which are responsible for validating that the access_token expired property. I don't see why the client API needs to vlidate this.

opinion?

**Comment by InDieTasten** [comment]
Imagine having a client, identity server and an API. Now, there's a good chance, that your id_token stored on the client is expiring. This is covered by your implementation. In this process it also refetches an access_token. But an access_token can have a significantly shorter lifetime than an id_token. So as soon as the access_token expires, the client would start to send expired bearer tokens to the apis. The apis will respond with 401 or similar.
My idea is, that the client should obtain a new access_tokens upon expiration, to always have a token to use for apis.

Is there something wrong with this approach? Right now I have short lifetimes for id_tokens, so that my access_tokens don't expire before them.

**Comment by damienbod** [comment]
Using the id_token token flow, you should not need to get new access_tokens. If the access_token expires before the id_token, I consider this a configuration bug.

Using the id_token flow, I would not use access_tokens...

So I don't see a use case per default.

You example is possible though...

We could begin the silent renew when either token expires, but per default it is not used. This can then be activated using the OpenIDImplicitFlowConfiguration class.

?

Greetings Damien

**Comment by InDieTasten** [comment]
Hm... maybe I've been misunderstanding the flow. I was thinking, that one would have id_tokens with long lifetimes, which can then be used to obtain short-lived access_tokens, thus enable more rapid granting/revoking of persmissions without having to make roundtrips or iframes to update access tokens.
Just a regular ajax call permitted by CORS for just the configured clients urls and the id_token_hint to make sure both client and identity server session are still talking about the same subject. (user agent might have signed in as a different user on identity server)

But configuring the id_token and access_token lifetimes to the same value, or having a config entry for `silentRenewAccessToken` or similar would be valid alternatives for me. I am still curious, whether my thought process is flawed or not.

Thanks for your help so far and kind regards
Max
