### ISSUE TITLE
light-weight copy-paste callback handler script for iframe callbacks

### ISSUE THREAD

**Issue by InDieTasten** [damienbod/AspNet5IdentityServerAngularImplicitFlow#82]
When implementing the oidc client in SPA environments, the silent-renew of id_tokens will load the entire app inside the iframe. It would be very convenient for consumers of this oidc client to be able to specify a second return url in the configuration for renewal of tokens to a second html document with just a small script to update the authorization data for the spa in the parent.

**Comment by damienbod** [comment]
added
