### ISSUE TITLE
Oidc-client

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#83]
As I understand you implemented your own version of oidc client to communicate with IDsrv4?

I am trying to implement silent sign in from here: https://github.com/IdentityModel/oidc-client-js/wiki

but that means I have to use oidc-client.js library. How do you combine this together with your example?

**Comment by damienbod** [comment]
This example implements the OIDC client in Angular. It supports SSO. If you use oidc-client.js, you can remove the complete auth.module from the application and add the oidc-client.js instead.

**Comment by damienbod** [comment]
this.oidcSecurityService.setStorage(cookieStorage);

**Comment by nukec** [comment]
@damienbod thanks. I am trying to implement silent sign in after user creates account(automatic logged in after creation) with your code, but I seem to not have option if i don't use IDsvr5 oidc-client.js ? 

My question is here: https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/issues/64

**Comment by damienbod** [comment]
SSO working with this client, Greetings Damien
