### ISSUE TITLE
public or private OidcSecurityService 

### ISSUE THREAD

**Issue by Brammii** [damienbod/AspNet5IdentityServerAngularImplicitFlow#84]
When the OidcSecurityService is injected into a constructor of a component, the public access specifier is used. 
``
constructor(public securityService: OidcSecurityService)
``

[AngularClient app.component.ts ](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/angularApp/app/app.component.ts)

In another project that I’m following, eShopOnContainers, both an Observable and a Subject are implemented in the security service. 

```
private authenticationSource = new Subject<boolean>();
authenticationChallenge$ = this.authenticationSource.asObservable
```
[eShopOnContainers security.service.ts](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebSPA/Client/modules/shared/services/security.service.ts)

The security service gets injected using the private access specifier and the component subscribes to the Observable. 
``
constructor(private service: SecurityService)
``
```
this.subscription = this.service.authenticationChallenge$.subscribe(res => {
  this.authenticated = res;
   });

```

[eShopOnContainers identity.ts](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebSPA/Client/modules/shared/components/identity/identity.ts)

@damienbod 
What do you think about this approach?

**Comment by damienbod** [comment]
I like your approach better, because the template has now dependencies then to the service. I only made it public to use the bool in the template, which is not very nice. I like your solution. If you want you can create a pull request and I add it, otherwise I'll  update.

Thanks for the issue

Greetings Damien

**Comment by damienbod** [comment]
This have been refactored now.
