### ISSUE TITLE
Unable to build and run the AngularClient project in VS2017

### ISSUE THREAD

**Issue by hmheng** [damienbod/AspNet5IdentityServerAngularImplicitFlow#85]
![image](https://user-images.githubusercontent.com/11830387/28499911-b7be9f6c-6ff2-11e7-8a43-48beeff4b770.png)

run with Ctrl + F5, it works but without debugging and it stucks at "Loading..." screen forever.

**Comment by damienbod** [comment]
Hi @hmheng You need to build the Angular application.

Try from the command first:

npm install
npm run build-dev

Visual Studio requires the node tools and that the right version is being used.

Greetings Damien

**Comment by damienbod** [comment]
@hmheng I'm closing this, let me know, if this is still an issue

Greetings Damien
