### ISSUE TITLE
Silent Renew gives error after 10 minutes

### ISSUE THREAD

**Issue by jbloem9** [damienbod/AspNet5IdentityServerAngularImplicitFlow#87]
When logging in identity server is called and credentials are entered.  User is successfully logged in. There are no errors in the console.
After 10 minutes of inactivity, there is an issue as attached, and the silent renew keeps running (see attached). When making any api calls after that the system returns a 401.

![error](https://user-images.githubusercontent.com/7578265/29010914-0ed310bc-7b83-11e7-861e-be1548d87038.PNG)
![renewrunning](https://user-images.githubusercontent.com/7578265/29010919-16d0384e-7b83-11e7-83e8-697c1d6c136b.PNG)

**Comment by damienbod** [comment]
Is this the first silent renew request?  looks like CORS needs to be activated for this request in the iframe

**Comment by damienbod** [comment]
Is this still a problem?

**Comment by jbloem9** [comment]
I ran my solution without any changes and did not get this error but the
silent renew is not working as I am getting 401 errors for any api calls. I
need to sit with the developer at our company who implemented this
originally. Will give you an answer next week.

**Comment by jbloem9** [comment]
When running the solution initially there are no errors and the silent renew works, running every 5 or 6 minutes without any issues.  Then after about 30 minutes, the silent renew gets stuck and stays in a state of
 "running" all the time.  The console has errors.
![appdata](https://user-images.githubusercontent.com/7578265/29255788-d3c4b37e-80f8-11e7-8e7c-0b5baadf3237.PNG)
![consoleerror](https://user-images.githubusercontent.com/7578265/29255789-d3c55284-80f8-11e7-90ed-1ddf7d8a747b.PNG)

**Comment by jbloem9** [comment]
I have upgraded to 1.3.8 and still got the same error.

**Comment by damienbod** [comment]
@jbloem9 Culd your try changing your X-Frame-options on your server? You're also using http, is this a demo app?

Greetings Damien

**Comment by jbloem9** [comment]
I will look into the X-Frame server options and let you know. This is an app we are developing for online auctions.  This is the STS:-
 
export const environment = {
    production: false,
    stsServer: 'https://localhost:44345',
    redirect_url: 'http://localhost:4200',
    post_logout_redirect_uri: 'http://localhost:4200',
    well_known_config_url:'https://localhost:44345/.well-known/openid-configuration',
    api_url:'https://localhost:44397'
};

**Comment by damienbod** [comment]
Hi @jbloem9 Just one other thing, you should not mix https and http

Greetings Damien

**Comment by jbloem9** [comment]
Hi Damien.

I have set the server to allow X-frames;
services.AddMvc();    services.AddAntiforgery(p => p.SuppressXFrameOptionsHeader = false);

I have changed the system to run using https only.  

In addition I have also set "AllowOfflineAccess" to true on the identity server settings.
 "Clients": [
    {
      "ClientId": "AuctionX.Web.Ui.Client.Ng",
      "ClientName": "Auction X web application",
      "AllowedGrantTypes": [ "implicit" ],
      "RequireConsent": false,
      "AllowedScopes": [ "openid", "profile", "email", "role", "api.write", "api.read" ],
      "RedirectUris": [ "https://localhost:4200" ],
      "PostLogoutRedirectUris": [ "https://localhost:4200" ],
      "LogoutUri": "https://localhost:4200",
      "AllowedCorsOrigins": [ "https://localhost:4200"],
      "AllowAccessTokensViaBrowser": true,
      "AccessTokenType": 0,
      "AllowOfflineAccess": true
 However, after 30 minutes I am still getting the same error.

**Comment by damienbod** [comment]
Does it fail at the first renew, of after n?

**Comment by jbloem9** [comment]
It's not the first renew. The renew runs for about 5 or 6 times without any
issues or errors in the console and then it fails. This is usually after
about 30 minutes.

**Comment by jbloem9** [comment]
Hi Damien.  I have attached 2 logs. One from the console and one from identity server.  Both logs show log entries where the silent renew is working and then at the point where it breaks.  
[ids-Silent renew.txt](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/files/1237438/ids-Silent.renew.txt)
[localhost-1503270417167.txt](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/files/1237439/localhost-1503270417167.txt)

**Comment by damienbod** [comment]
Looks like the Identity session on the IdentityServer4 timed out.

**Comment by jbloem9** [comment]
Hi Damien.  After upgrading to version 1.3.12 of the angular-auth-oidc-client and implementing changes as suggested for Issue Number #71 in angular-auth-oidc-client , this no longer gives an error.  

However the silent renew is running continually. Once the silent renew starts, it seems to be stuck in an endless loop, being called over and over again, instead of just running every 5 minutes. 

Below is attached a screen shot of the application storage where the silent renew is seen to be running.

![silentrenewrunning](https://user-images.githubusercontent.com/7578265/29951751-ed6a4dec-8f18-11e7-9f23-3e70f3eabd39.PNG)

I have also attached a log of the console.  All entries in this log were generated over a period of just 1 minute.

[SilentRenewLoopingLog.txt](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/files/1268903/SilentRenewLoopingLog.txt)

**Comment by khennny** [comment]
Hello, I also have this issue. STS server is Identity server 4.After successful login,the silent renew call keeps running in infinite loop.I changed my client config to point to Google and I was able to login and no infinite silent renew running. 
Any help would be greatly appreciated.

**Comment by damienbod** [comment]
@khennny Does the google OIDC support silent renew? The google OIDC does not of all the OpenID Connectg apis.

Greetings Damien

**Comment by khennny** [comment]
It seems the problem was with the cookie configuration on identity server 4 hosting project. By default the "CookiePolicyOptions.CheckConsentNeeded" is set to true, I changed it to false and the silent renew infinite loop was gone and was able to generate new token.

 services.Configure<CookiePolicyOptions>(options =>
            {                
                options.CheckConsentNeeded = context => false;
                options.MinimumSameSitePolicy = SameSiteMode.None;                              
            });
Am using .net core 2.1,VS 2017.
I don't know if this would have any security implication.I would like to advised if it is a good move.

**Comment by vejandla** [comment]
@jbloem9 did you find a solution for your problem?
