### ISSUE TITLE
Update ASP.NET Core 2.0

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#88]

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by damienbod** [comment]
Have to wait for IdentityServer4 to update, and it's sub packages

**Comment by MovGP0** [comment]
ID4 itself doesn't seem to be the issue (it works fine with .NET Core 2.0). However, there are some Microsoft package dependencies that are not updated yet.

**Comment by damienbod** [comment]
@MovGP0 yep.

**Comment by damienbod** [comment]
TODO:
- fix otherLogins in ManageController
- secure files API download file bug
- API token validation

**Comment by damienbod** [comment]
updated, that took long :)
