### ISSUE TITLE
logoff() runs GET "account/logout" from IDP and receives 404 response

### ISSUE THREAD

**Issue by RGVGreatCoder** [damienbod/AspNet5IdentityServerAngularImplicitFlow#90]
Executing OidcSecurityService.logoff() from my client (ASPNET MVC Core 2.0 Angular 4.3.6) ends up making this **Get** Request to my IDP (ASPNET MVC Core 1.1.2/IdentityServer4 1.5.2): "https://localhost:44333/account/logout?logoutId=ab01767bb9e09988434df8a7bc32e260". My IDP has only one "account/logout" and is a **Post** method. The debug output log shows a 404 response code.

The client setupModule has **post_logout_redirect_uri** = 'https://localhost:44345/signout-callback-oidc' and IDP has **PostLogoutRedirectUris** = new List<string>() { "https://localhost:44345/signout-callback-oidc" }.

I was expecting my IDP redirecting back to my client in a state before logging in.

Am I missing something? :-\

**Comment by damienbod** [comment]
It could/should redirect back to your client which logged in, At present , you need to click a link in the view. This could be removed. I look at this fully, after I update to .NET Core 2.0

**Comment by RGVGreatCoder** [comment]
Thank you again for your prompt response! 👍 .. :)

Sorry to ask but, what do you mean by "click a link in the view"? What view? Could you please elaborate on this view you mention? :-\

By the way, I created another client with ASPNET MVC Core 1.1.2/Angular 4.3.6 and it behaves the same. 

The issue here, I believe, is that my IDP does not have a logout method to be called with an HTTP GET request, which is what your function "OidcSecurityService.logoff()" does. The logout method (generated out of the box when creating the client with ASPNET MVC Identity Authentication) is called with a POST Request. So that tells me I need to code an HTTP GET "account/logout" in my IDP.  To learn if I may be correct, I checked this sample link "https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountController.cs" and sure enough found this GET method:

    [HttpGet]
    public async Task<IActionResult> Logout(string logoutId)
    {
        var vm = await _account.BuildLogoutViewModelAsync(logoutId);
        if (vm.ShowLogoutPrompt == false)
        {
            // no need to show prompt
            return await Logout(vm);
        }
        return View(vm);
    }

When added to my code, your "OidcSecurityService.logoff()" function finally reaches this GET "account/logout" method (I probably need to declare the "AccountService _account" object, but I am not sure though).

Am I going the right path or am I making things more complicated than necessary? 
Again, can you please elaborate what you meant by "click a link in the view" to see if your approach is enough? I really appreciate your time and effort on this. You are really, really awesome! :)

**Comment by RGVGreatCoder** [comment]
Hello Damienbod. Do you have any new comments from this issue I posted some days ago? :)
