### ISSUE TITLE
Support to login silently without being redirected to identity server

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#91]
I am still struggling with this.

Is there any way we can pass username and password to Identity server authorisation endpoint silently in background without user being redirected to identity server website with Grant Type Implicit? Something like client credentials grant type but implicit. I read silent signin is possible, but not sure if implemented in this example? Can you show example damien?

**Comment by nukec** [comment]
Is this planned to be implemented? UserManager.signinSilent()

**Comment by MovGP0** [comment]
take a look at the [Resource Owner Password Grant](http://docs.identityserver.io/en/release/quickstarts/2_resource_owner_passwords.html).

**Comment by nukec** [comment]
@MovGP0 I am not confident about security of that grant type. There is an option to do it with Implicit flow with usage of signInSilent after registration process is done, but no examples.

**Comment by lanovoy** [comment]
The only proper option for browser apps is to use Implicit Grant flow.
