### ISSUE TITLE
Sample Using HttpClient with HttpInterceptor

### ISSUE THREAD

**Issue by RGVGreatCoder** [damienbod/AspNet5IdentityServerAngularImplicitFlow#92]
Hello damienbod. This post is not an issue. I am posting this sample code to share in your blog using HttpClient with HttpInterceptor as a way of thanking you with a small contribution from me, for sharing your library. I am basing my code from what I learned on this page: https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8.  I hope it helps anyone! :)

A requirement is to upgrade Angular to 4.3.6 (like shown on your package.json file). The Interceptor will pick all send requests and responds. The interceptor will set the access token automatically and can handle response codes, like redirecting to login when receiving a 401. 

On the out of the box web application generated by using the Angular template in Visual Studio 2017 ASPNET Core 2.0, I used HttpClient and HttpInterceptor as follows: 

**HttpInterceptor**:

    import { Injectable } from '@angular/core';
    import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor, HttpResponse, HttpErrorResponse } from '@angular/common/http';
    import { Router } from '@angular/router';
    import { OidcSecurityService } from 'angular-auth-oidc-client';
    import { Observable } from 'rxjs/Observable';

    @Injectable()
    export class TokenInterceptor implements HttpInterceptor {
        constructor( public oidcSecurityService: OidcSecurityService, private router: Router ) { }
        intercept( request: HttpRequest<any>, next: HttpHandler ): Observable<HttpEvent<any>> {

            request = request.clone( {
                setHeaders: {
                    Authorization: `Bearer ${this.oidcSecurityService.getToken()}`
                }
            } );

            return next.handle( request ).do(( event: HttpEvent<any> ) => {
                if ( event instanceof HttpResponse ) {
                    // do stuff with response if you want
                }
            }, ( err: any ) => {
                if ( err instanceof HttpErrorResponse ) {
                    if ( err.status === 401 ) {
                        //this.router.navigate( ['/unauthorized'] );
                        this.oidcSecurityService.authorize();
                    }
                }
             } );
        }
    }

**HttpClient**: 

        import { Component, OnInit } from '@angular/core';
        import { HttpClient, HttpHeaders } from '@angular/common/http';
        import { OidcSecurityService } from 'angular-auth-oidc-client';

        @Component( {
            selector: 'fetchdata-auth',
            templateUrl: './fetchdataauth.component.html'
        } )
        export class FetchDataAuthComponent implements OnInit {
            public forecasts: WeatherForecast[];

            constructor( private httpClient: HttpClient, private oidcSecurityService: OidcSecurityService ) { }

            ngOnInit() {
                this.httpClient.get<WeatherForecast[]>( 'https://localhost:44382/api/sampledata/WeatherValues')
                    .subscribe(
                    data => {
                        this.forecasts = data;
                    },
                    err => {
                        console.log( 'An error occurred.' );
                    }
                )
            }

        }

    interface WeatherForecast {
        dateFormatted: string;
        temperatureC: number;
        temperatureF: number;
        summary: string;
    }

Updated the app.module.ts as follows:

    import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
    ...
    @NgModule({
        declarations: [
            ....
        ],
        imports: [
            HttpClientModule,
            ...
        ],
        providers: [ 
            { provide: HTTP_INTERCEPTORS, useClass: TokenInterceptor, multi: true},
            ...
        ]
    })
    export class AppModuleShared { ... }

**Comment by damienbod** [comment]
@RGVGreatCoder thanks

I'll update this, was meaning to switch to the new http clinet for a while. If you want, you can create a PR and I'll merge it, otherwise update using your code.

Thanks Damien
