### ISSUE TITLE
Changes in code not updating

### ISSUE THREAD

**Issue by phamquanghung263** [damienbod/AspNet5IdentityServerAngularImplicitFlow#93]
Hi, I'm using VS2017 to debug.
When I change some codes (TS or html template), then F5, it was not updated. I must run npm build cmd to get the changes.
So, how to fix it.
Thanks.

**Comment by damienbod** [comment]
Hi @phamquanghung263 

You can use the npm watch

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/AngularClient/package.json#L18

If xyou install the npm task runner in VS, this will run automatically

Greetings Damien

**Comment by phamquanghung263** [comment]
Thank you mr @damienbod.
I've seen my problem in task runner's console. It's cause of the Visual's Node module version not same as my global version. So I just update Visual's Node version and  the changes are updated (when I re-debug visual).
I've another question, when i make changes in html template file, how to only refresh browser (not stop and start debug) to take the changes?
Thanks.
