### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ChinhDuong** [damienbod/AspNet5IdentityServerAngularImplicitFlow#94]
I get Uncaught SyntaxError: Unexpected identifier when run AngularClient. Can anyone help me to fix it. Thank in advance
![image](https://user-images.githubusercontent.com/12442221/31066257-d4dcf02a-a775-11e7-95c8-149c813e2045.png)

**Comment by damienbod** [comment]
Hi @ChinhDuong  the SPA application is not build

cmd:

npm install
npm run build-dev

or install the npm task runner in VS

Greetings Damien

**Comment by ChinhDuong** [comment]
Thank you so much
