### ISSUE TITLE
Angular 5.1.0 and TypeScript 2.6

### ISSUE THREAD

**Issue by lanovoy** [damienbod/AspNet5IdentityServerAngularImplicitFlow#96]
Angular 5.1.0 does NOT support this version of the typescript yet. The last one they support is 2.5.3

**Comment by damienbod** [comment]
Will downgrade typescript, was hoping that it would support this soon. This needs to be changed in the package.json file.

Thanks for reporting

Greetins Damian

**Comment by lanovoy** [comment]
Don't forget about the lock file. The actual version is in the package-lock.json.

**Comment by damienbod** [comment]
fixed, thanks for reporting
