### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by mabouchalkha** [damienbod/AspNet5IdentityServerAngularImplicitFlow#97]
Hi,
thank you for this sample.
i don't know if you can help me.
i want to implement a user registration in the SPA application because isn't related to Identity Server (i don't want to be the responsibility of identityServer). So my problem is i just I can not use UserManager (IdentityDbContext) of IdentityServer to create a user in the API (ResourceServer).
do you have any idea.

thank you

**Comment by damienbod** [comment]
@mabouchalkha 
´´´
private readonly UserManager<ApplicationUser> _userManager;

public Class_XXXXX(UserManager<ApplicationUser> userManager)
{
	_userManager = userManager;
}

method:

var user = new ApplicationUser { UserName = email, Email = email };

var result = await _userManager.CreateAsync(user);
´´´

**Comment by mabouchalkha** [comment]
hi, thank you for youe quick response.

I did that but when i add

`services.AddIdentity<ApplicationUser, IdentityRole>().AddEntityFrameworkStores<ApplicationDbContext>().AddDefaultTokenProviders();`

the api doesn't return 401 but it redirect to account/login?returnUrl instead.

thabnk you
